spring:
  datasource:
    url: jdbc:h2:mem:querydsl
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true # 쿼리들을 JPQL로 변환해서 알려준다.

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.TYPE: DEBUG
