spring:
  datasource:
    url: jdbc:h2:mem:querydsl
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.TYPE: DEBUG
